# instalation of postgresql server version 9.4 on top of amazon linux image
# creation of one user docker  - db docker- password docker to access the server.



from amazonlinux

RUN echo "NETWORKING=yes" > /etc/sysconfig/network

RUN yum -y install postgresql94-server 
RUN yum -y install postgresql94


 